# Generated by Django 5.2.3 on 2025-07-06 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0002_task_subtask_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('task', 'name'), name='unique_subtask_per_task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_task_per_user'),
        ),
    ]
