# Generated by Django 5.2.3 on 2026-06-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0004_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
