# Generated by Django 5.2.3 on 2026-06-22 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0005_subtask_deleted_at_task_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
