# Generated by Django 5.2.3 on 2026-06-22 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0006_alter_timeentry_clock_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('reminder_lead_minutes', models.PositiveIntegerField(default=15)),
                ('link_token', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('link_token_created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('connected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
