# Generated by Django 5.2.3 on 2026-06-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0007_usertelegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='ticktask.calendarevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'kind'), name='unique_reminder_per_event_kind')],
            },
        ),
    ]
