# Generated by Django 5.2.3 on 2026-06-23 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0009_useraccessrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sentreminder',
            name='unique_reminder_per_event_kind',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'Does not repeat'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sentreminder',
            name='occurrence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='sentreminder',
            constraint=models.UniqueConstraint(fields=('event', 'kind', 'occurrence'), name='unique_reminder_per_event_kind_occurrence'),
        ),
    ]
