# Generated by Django 5.2.3 on 2026-06-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0010_remove_sentreminder_unique_reminder_per_event_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegramsettings',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
