# Generated by Django 5.2.3 on 2026-08-16 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktask', '0012_notegroup_note_notegroup_unique_note_group_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='google_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='GoogleCalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default='', max_length=2048)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=2048)),
                ('token_expiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('calendar_id', models.CharField(blank=True, default='primary', max_length=255)),
                ('sync_token', models.CharField(blank=True, default='', max_length=1024)),
                ('connected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarPendingDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deletions', to='ticktask.googlecalendaraccount')),
            ],
        ),
    ]
